### PR TITLE
Update to sdk

### PR DESCRIPTION
**Pull request by alcortesm**
Merge #14 and #15 first, this means the only relevant commit in this PR is https://github.com/bblfsh/bash-driver/pull/16/commits/c59790bd31111edcb892402b8b916cf90108e1d3.

### CODE REVIEW

**Comment by alcortesm** [comment]
Umm, the CI is failing because the order of the map elements in the native output is not what I upload in the tests directory.  This has to do with the prettyprinting I guess.

**Comment by alcortesm** [comment]
OK, fixed it by sorting my `tests/*.native` as the driver expected, but I think this is wrong.

**Comment by alcortesm** [comment]
Posible solutions:
1. don't check `tests/*.native` in the integration tests, as they have nothing to do with intergration.
2. don't use `cmp` to compare JSONs but use a tool that doesn't care about the order of the objects elements.
3. make the expected order of the JSON objects element explicit, alphabetic for instance.

The bests ones for me are 1 (and maybe 2).

**Comment by smola** [comment]
These files are always generated from `protocol/driver/driver.go` and they are outputted in a deterministic way. Since `status` and `error` are defined in a Go struct, they are printed in the order they are defined.

In the future we'll probably port tests (i.e. `it.bash`) to Go, and use a comparison function that is independent of order. At the moment, just use what `make integration-test` generates.

**Pull request merged**
